databases:
  - name: hrm-db
    plan: free
    databaseName: hrmdb
    user: hrmdbuser

services:
  - type: web
    name: hrm-system
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn app.asgi:application -k uvicorn.workers.UvicornWorker --chdir app"
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: hrm-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: hrm-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: hrm-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: hrm-db
          property: password
      - key: DATABASE_URL
        fromDatabase:
          name: hrm-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
