# Generated by Django 3.2.25 on 2025-04-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_employee_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
