# Generated by Django 3.2.25 on 2025-04-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employee_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
