# Generated by Django 3.2.25 on 2025-04-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_employee_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
